services:
  eoinhay-es:
    build: app/.
    volumes:
      - ./content:/usr/src/app/content:ro
    restart: unless-stopped
    networks:
      - proxy-network
      - default
networks:
  proxy-network:
    external: true
